name: Go CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Build
        run: go build -o assume-role

      - name: Archive Release
        uses: actions/upload-artifact@v4
        with:
          name: assume-role
          path: assume-role
          overwrite: true
          compression-level: 0
          if-no-files-found: error